version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
environment:
  PROGET_API_KEY:
    secure: cK5vivAu043l5udO8/xlrju1zldGzrHfQxWXVNeyAfg=
before_build:
- ps: nuget restore "Git\Git.sln"
build:
  verbosity: minimal
after_build:
- pwsh: >-
    $toolPath = "$($env:USERPROFILE)\inedoxpack.zip"

    (New-Object Net.WebClient).DownloadFile('https://s3.amazonaws.com/cdn.inedo.com/tools/inedoxpack.zip', $toolPath)

    Expand-Archive -Path $toolPath -DestinationPath .\Tools\inedoxpack

    .\Tools\inedoxpack\inedoxpack.exe ".\Git\Git.InedoExtension\bin\Release\Git.dll" ".\Git.upack"
    .\Tools\inedoxpack\inedoxpack.exe ".\Git\GitHub.InedoExtension\bin\Release\GitHub.dll" ".\GitHub.upack"
    .\Tools\inedoxpack\inedoxpack.exe ".\Git\GitLab.InedoExtension\bin\Release\GitLab.dll" ".\GitLab.upack"

    $upackFilePathGit = (Resolve-Path ".\Git.upack").Path
    $upackFilePathGitHub = (Resolve-Path ".\GitHub.upack").Path
    $upackFilePathGitLab = (Resolve-Path ".\GitLab.upack").Path

    $queryGit = (`
      "?name=Git" + `
      "&version=$($env:APPVEYOR_BUILD_VERSION)" + `
      "&title=Git" + `
      "&description = [Uri]::EscapeDataString('Source control operations for Git.')" `
    );
    $queryGitHub = (`
      "?name=GitHub" + `
      "&version=$($env:APPVEYOR_BUILD_VERSION)" + `
      "&title=GitHub" + `
      "&description = [Uri]::EscapeDataString('Source control, release management, and issue tracking integration for GitHub.')" `
    );
    $queryGitLab = (`
      "?name=GitLab" + `
      "&version=$($env:APPVEYOR_BUILD_VERSION)" + `
      "&title=GitLab" + `
      "&description = [Uri]::EscapeDataString('Source control and issue tracking integration for GitLab.')" `
    );

    Invoke-RestMethod -Method Put `
       -Uri ('https://56.inedo.com:8624/upack/Appveyor/upload' + $queryGit) `
       -ContentType 'application/zip' `
       -Body ([IO.File]::ReadAllBytes($upackFilePathGit)) `
       -Headers @{ 'X-ApiKey' = $($env:PROGET_API_KEY) } `
       -SkipCertificateCheck

    Invoke-RestMethod -Method Put `
       -Uri ('https://56.inedo.com:8624/upack/Appveyor/upload' + $queryGitHub) `
       -ContentType 'application/zip' `
       -Body ([IO.File]::ReadAllBytes($upackFilePathGitHub)) `
       -Headers @{ 'X-ApiKey' = $($env:PROGET_API_KEY) } `
       -SkipCertificateCheck

    Invoke-RestMethod -Method Put `
       -Uri ('https://56.inedo.com:8624/upack/Appveyor/upload' + $queryGitLab) `
       -ContentType 'application/zip' `
       -Body ([IO.File]::ReadAllBytes($upackFilePathGitLab)) `
       -Headers @{ 'X-ApiKey' = $($env:PROGET_API_KEY) } `
       -SkipCertificateCheck
artifacts:
- path: Git.upack
- path: GitHub.upack
- path: GitLab.upack
nuget:
  account_feed: true
